In [1]:
import pandas as pd

In [5]:
file = "data.csv"
df= pd.read_csv(file)
df

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
0,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423.0,6.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969.0,8.0
2,Aamir Khan,Dangal,2016,Sports/Drama,2027.0,8.4
3,Deepika Padukone,Piku,2015,Comedy/Drama,140.0,7.6
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238.0,8.0
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377.0,8.1
6,Hrithik Roshan,War,2019,Action/Thriller,475.0,6.5
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220.0,7.8
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586.0,7.7
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137.0,8.2

In [9]:
##column select
df['ACTOR']

0      Shah Rukh Khan
1         Salman Khan
2          Aamir Khan
3    Deepika Padukone
4       Ranveer Singh
5        Katrina Kaif
6      Hrithik Roshan
7          Alia Bhatt
8       Ranbir Kapoor
9      Kangana Ranaut
Name: ACTOR, dtype: object

In [13]:
df[['ACTOR','IMDB']]   ##only returns view-copy no changes in real dataframe

              ACTOR  IMDB
0    Shah Rukh Khan   6.1
1       Salman Khan   8.0
2        Aamir Khan   8.4
3  Deepika Padukone   7.6
4     Ranveer Singh   8.0
5      Katrina Kaif   8.1
6    Hrithik Roshan   6.5
7        Alia Bhatt   7.8
8     Ranbir Kapoor   7.7
9    Kangana Ranaut   8.2

In [15]:
df.loc[1]   #defualt by row levels --they can bechanged in most cases
df.iloc[1]   ##finds by index constant

ACTOR              Salman Khan
FILM         Bajrangi Bhaijaan
YEAR                      2015
GENRE             Drama/Action
BOXOFFICE                969.0
IMDB                       8.0
Name: 1, dtype: object

In [21]:
df.loc[9, "IMDB"]   ##LOCATING PARTICULAR CELL using loc
df.iloc[9, 5]    ##locating to cell through iloc  [9th index's 5th imdb cell]

8.2

In [30]:
df.loc[0:2, ("ACTOR", "IMDB", "FILM")]    ##slicing

df.iloc[0:2, [1,5]]

                FILM  IMDB
0    Chennai Express   6.1
1  Bajrangi Bhaijaan   8.0

In [28]:
df.iloc[0:2, [0, 5]]

            ACTOR  IMDB
0  Shah Rukh Khan   6.1
1     Salman Khan   8.0

In [31]:
df.at[0, "ACTOR"]     ## at --Optimised for single

'Shah Rukh Khan'

In [32]:
df.iat[0, 0]             ##iat -- index focused just like coordinates

'Shah Rukh Khan'

In [40]:
#########FILTERING

df[df['IMDB']>7]    ##FILMS HAVING RATING MORE THATN 7

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969.0,8.0
2,Aamir Khan,Dangal,2016,Sports/Drama,2027.0,8.4
3,Deepika Padukone,Piku,2015,Comedy/Drama,140.0,7.6
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238.0,8.0
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377.0,8.1
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220.0,7.8
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586.0,7.7
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137.0,8.2

In [51]:
df[(df['YEAR']>2018) &(df['IMDB']>6) ]

            ACTOR       FILM  YEAR            GENRE  BOXOFFICE  IMDB
4   Ranveer Singh  Gully Boy  2019    Musical/Drama      238.0   8.0
6  Hrithik Roshan        War  2019  Action/Thriller      475.0   6.5

In [56]:
df.query("YEAR >2016 and IMDB >7 and BOXOFFICE>300")    ##HUMAN LIKE LANGUAGE

           ACTOR   FILM  YEAR            GENRE  BOXOFFICE  IMDB
8  Ranbir Kapoor  Sanju  2018  Biography/Drama      586.0   7.7