In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
0,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423,6.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969,8.0
2,Aamir Khan,Dangal,2016,Sports/Drama,2027,8.4
3,Deepika Padukone,Piku,2015,Comedy/Drama,140,7.6
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,8.0
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377,8.1
6,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220,7.8
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586,7.7
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137,8.2

In [6]:
df.sort_values("YEAR") ##sorts ascending order

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377,8.1
0,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423,6.1
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137,8.2
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969,8.0
3,Deepika Padukone,Piku,2015,Comedy/Drama,140,7.6
2,Aamir Khan,Dangal,2016,Sports/Drama,2027,8.4
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220,7.8
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586,7.7
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,8.0
6,Hrithik Roshan,War,2019,Action/Thriller,475,6.5

In [7]:
df.sort_values("YEAR", ascending=False)

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,8.0
6,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220,7.8
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586,7.7
2,Aamir Khan,Dangal,2016,Sports/Drama,2027,8.4
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969,8.0
3,Deepika Padukone,Piku,2015,Comedy/Drama,140,7.6
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137,8.2
0,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423,6.1
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377,8.1

In [11]:
df.sort_values(["YEAR", "IMDB"]) ##if year ties (same in 2 then the IMBD NOW sorts and acts as secondary sort helper)

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377,8.1
0,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423,6.1
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137,8.2
3,Deepika Padukone,Piku,2015,Comedy/Drama,140,7.6
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969,8.0
2,Aamir Khan,Dangal,2016,Sports/Drama,2027,8.4
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586,7.7
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220,7.8
6,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,8.0