In [1]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees, departments, on ="DeptID")  #INNER JOIN -no NAN

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees, departments, on="DeptID", how="left")  #left join employees more prioritised

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees, departments, on="DeptID", how="right")  #right join department more prioritised

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [9]:
pd.merge(employees, departments, on="DeptID", how="outer")  #outer join --SHOWS ALL NAN

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [17]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score": [423,123]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"] , "age" : [12,45]})

###concatination of data frames

In [19]:
pd.concat([df1, df2])  ## axis =1  for horizontally

      Name  Score   age
0    Alice  423.0   NaN
1      Bob  123.0   NaN
0  Charlie    NaN  12.0
1    David    NaN  45.0