In [1]:
import pandas as pd
# from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_excel("iris_train.xlsx")

In [3]:
data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         2.6          6.9         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         3.0          6.1         2.3  Iris-virginica

In [4]:
x= data.iloc[:, :-1] 
x

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         2.6          6.9         2.3
3            7.7         2.8          6.7         2.0
4            7.7         3.0          6.1         2.3
..           ...         ...          ...         ...
114          4.5         2.3          1.3         0.3
115          4.4         2.9          1.4         0.2
116          4.4         3.0          1.3         0.2
117          4.4         3.2          1.3         0.2
118          4.3         3.0          1.1         0.1

[119 rows x 4 columns]

In [5]:
y = data.iloc[:, -1]
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
114       Iris-setosa
115       Iris-setosa
116       Iris-setosa
117       Iris-setosa
118       Iris-setosa
Name: class, Length: 119, dtype: object

In [6]:
# model = DecisionTreeClassifier()
model = RandomForestClassifier()

In [7]:
model.fit(x, y)

RandomForestClassifier()

In [8]:
prediction = model.predict([[2.5, 5.6, 3.4, 4.4]])
prediction

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['Iris-virginica'], dtype=object)

In [9]:
test_data = pd.read_excel("iris_test.xlsx")

In [10]:
test_data.head()

   sepallength  sepalwidth  petallength  petalwidth            class
0          6.3         2.8          5.1         1.5   Iris-virginica
1          6.3         3.4          5.6         2.4   Iris-virginica
2          6.3         2.5          5.0         1.9   Iris-virginica
3          6.2         2.2          4.5         1.5  Iris-versicolor
4          6.2         2.9          4.3         1.3  Iris-versicolor

In [11]:
x_test=test_data.iloc[:, :-1]
x_test

    sepallength  sepalwidth  petallength  petalwidth
0           6.3         2.8          5.1         1.5
1           6.3         3.4          5.6         2.4
2           6.3         2.5          5.0         1.9
3           6.2         2.2          4.5         1.5
4           6.2         2.9          4.3         1.3
5           6.2         2.8          4.8         1.8
6           6.2         3.4          5.4         2.3
7           6.1         2.9          4.7         1.4
8           6.1         2.8          4.0         1.3
9           6.1         2.8          4.7         1.2
10          6.1         3.0          4.6         1.4
11          6.1         3.0          4.9         1.8
12          6.1         2.6          5.6         1.4
13          6.0         2.2          4.0         1.0
14          6.0         2.9          4.5         1.5
15          6.0         2.7          5.1         1.6
16          6.0         3.4          4.5         1.6
17          6.0         2.2          5.0         1.5
18          6.0         3.0          4.8         1.8
19          5.9         3.0          4.2         1.5
20          5.9         3.2          4.8         1.8
21          5.9         3.0          5.1         1.8
22          5.8         4.0          1.2         0.2
23          5.8         2.7          4.1         1.0
24          5.8         2.7          3.9         1.2
25          5.8         2.6          4.0         1.2
26          5.8         2.7          5.1         1.9
27          5.8         2.8          5.1         2.4
28          5.8         2.7          5.1         1.9
29          5.7         4.4          1.5         0.4
30          5.7         3.8          1.7         0.3

In [12]:
predictions =model.predict(x_test.values)
predictions

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [13]:
y_test= test_data.iloc[:, -1] 
y_test

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3     Iris-versicolor
4     Iris-versicolor
5      Iris-virginica
6      Iris-virginica
7     Iris-versicolor
8     Iris-versicolor
9     Iris-versicolor
10    Iris-versicolor
11     Iris-virginica
12     Iris-virginica
13    Iris-versicolor
14    Iris-versicolor
15    Iris-versicolor
16    Iris-versicolor
17     Iris-virginica
18     Iris-virginica
19    Iris-versicolor
20    Iris-versicolor
21     Iris-virginica
22        Iris-setosa
23    Iris-versicolor
24    Iris-versicolor
25    Iris-versicolor
26     Iris-virginica
27     Iris-virginica
28     Iris-virginica
29        Iris-setosa
30        Iris-setosa
Name: class, dtype: object

In [14]:
actual = y_test.values
actual

array(['Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [15]:
count = 0
for i in range (0, len(actual)):
    if(actual[i]== predictions[i]): 
        count+=1
accuracy = count/(len(actual)) *100

In [16]:
print(f"The overall accuracy of our model is {accuracy} %")

The overall accuracy of our model is 87.09677419354838 %